import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {getCoins} from '../providers'
import styles from '../styles/Home.module.scss'

const Home: NextPage = ({coinData}) => {
  const {data = [], error = ''} = coinData;
  return (
    <div className={styles.container}>
      <Head>
        <title>Coin360</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error && error}
      {data && data.map((coin) => {
        return `${coin.s} `
      })}
    </div>
  )
}

export async function getStaticProps() {
  const coinData = await getCoins()
  return {
    props: {coinData}, // will be passed to the page component as props
  }
}

export default Home
