import type { NextPage } from 'next'
import Head from 'next/head'
import {getCoins} from '../providers'
import {ICoinData} from "../interface/coin";
import styles from '../styles/Home.module.scss'

interface ICoinPage {
    coinData: ICoinData
}

const Home: NextPage<ICoinPage> = ({coinData}) => {
  const {data = [], error = ''} = coinData;

  const transformedData = data.filter(coin => coin.p !== 0)

  return (
    <div className={styles.container}>
      <Head>
        <title>Coin360</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error && error}
      <table>
        <tbody>
        {transformedData.map((coin) => {
          return (
              <tr key={coin.s}>
                <td>{coin.s}</td>
                  {transformedData.map((coin) => {
                    return (
                        <td key={coin.s}>
                          <div className="cell-title">{coin.s}</div>
                          <div className="cell-info">{coin.ch}%</div>
                        </td>
                    )
                  })}
              </tr>
          )
        })}
        </tbody>
      </table>
    </div>
  )
}

export async function getStaticProps() {
  const coinData = await getCoins()
  return {
    props: {coinData}, // will be passed to the page component as props
  }
}

export default Home
